export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  AUD = 'AUD',
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  HKD = 'HKD',
  JPY = 'JPY',
  NZD = 'NZD',
  SGD = 'SGD',
  SEK = 'SEK',
  KRW = 'KRW',
  RUB = 'RUB',
  TRY = 'TRY',
  INR = 'INR',
  BRL = 'BRL',
  AED = 'AED',
  VND = 'VND',
  THB = 'THB',
  IDR = 'IDR',
  MYR = 'MYR',
  MXN = 'MXN',
  BGN = 'BGN',
  NOK = 'NOK',
}
