
export enum UserActionType {
    USER_LISTING = 'USER_LISTING',
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',
    USER_SET_PASSWORD = 'USER_SET_PASSWORD',
    USER_SET_ROLE = 'USER_SET_ROLE',
    USER_SET_PERMISSIONS = 'USER_SET_PERMISSIONS',
    USER_SET_ACTIVE = 'USER_SET_ACTIVE',
    USER_SET_ROLE_PERMISSIONS = 'USER_SET_ROLE_PERMISSIONS',
    USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
    USER_SET_DEPARTMENT = 'USER_SET_DEPARTMENT',
}